#!/usr/bin/perl

#echo $@

#echo "SUBMENU|Title|Item1|Item2|Item3"

$| = 1;
#print "LOCATION:https://greynir.is\n";
#sleep 5;
#print "LOCATION:http://lemurinn.is\n";
#sleep 5;
#print "LOCATION:http://isnic.is\n";


#foreach(@ARGV) {
#     print "$_\n";
#}

for (my $i = 0; $i < 100000; $i++){
#sleep 1;
    print "$i Hey\n";
#        sleep 1;
}


# If 0 arguments, we show menu
#if (!scalar(@ARGV)) {
#print "Life's but a walking shadow, a poor player\n";
#print "That struts and frets his hour upon the stage\n";
#print "And then is heard no more.\n";
#} else {
## We get the menu title as an argument
## and feed it to the Mac OS X voice synthesizer
#system("/usr/bin/say \"$ARGV[0]\"");
#}
