#!/usr/bin/perl -w
# Test script for ScriptExec binary
#

#sleep 3;
#for ($i = 0; $i < 100; $i++)
#{#
#print "$i" . "\n";
#}
#$i = 0;
#foreach (@ARGV)
#{
	#		print "$_\";
	#sleep 1;
#}
#$i = 0;
#while ($i < 9000)
#{ print "$i: Smusmu\n"; 
#
#	print "PROGRESS:" . int($i / 100) . "\n";
#
#	$i++;
#}
local $| = 1;
#print "Arguments:\n";
#
#foreach (@ARGV) { print "\t" . $_ . "\n"; }

#if (scalar(@ARGV) > 0) {
#    system("/usr/bin/say '$ARGV[0]'");
#} else {
#    
#    print "Hey\n";
#    print "You\n";
#    print "There\n";
#}
#

#print "MENUITEMICON|appIcon.icns|Menu item icon can be a bundled image\n";
#print "MENUITEMICON|/Library/Application Support/Apple/iChat Icons/Flags/Iceland.png|Or an image on the file system\n";
#print "MENUITEMICON|http://sveinbjorn.org/images/andlat.png|Or even a URL!\n";


#use Shell;
#
#print ps("caux");

#!/usr/bin/perl

#print "<html><body bgcolor='#F1F1DE'><center><font color='blue'><h1>Hello, World</h1></font></center></body></html>\n";

my $i = 0;
while ($i < 1) {
    print "PROGRESS:$i";
    $i++;

}

#sleep 1;
# If 0 arguments, we show menu
#if (!scalar(@ARGV)) {
#    print "Life's but a walking shadow, a poor player\n";
#    print "That struts and frets his hour upon the stage\n";
#    print "And then is heard no more.\n";
#} else {
#    system("/usr/bin/say \"$ARGV[0]\"");
#}


#if (!scalar(@ARGV)) {
#    print system('ps cax | grep httpd');
#    print "\nRestart";
#} elsif ($ARGV[0] eq 'Restart') {
#    system("/usr/bin/say Hello, Dave. It can only be attributable to human error");
#}


#print "PROGRESS:40\n";
#print "DETAILS:SHOW\n";
#print "DETAILS:HIDE\n";
#print "QUITAPP\n";

#print "DETAILS:HIDE\n";


#print "PROGRESS:100\n";
#	print STDOUT "Doing $i\r";
#	print "Number $i\n";
#	print "PROGRESS:$i\n";
#	print "http://gnu.org\n";
#	$i++;

#print "Done";
#print "Hola";

#scp $2 root@arakkis:/tmp/
#touch /Users/sveinbjorn/Desktop/YES.txt
#echo PROGRESS:30
#echo Hello 1
#find /Users/
#echo PROGRESS:60
#echo Hello 2
#sleep 1
#echo PROGRESS:90
#echo Hello 3
#sleep 1
#perl anotherScript 2>&1 
#find /www/sveinbjorn/cgi-bin/
#echo "FINIDO"
#sleep 1