# GitHub Actions CI build

name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: gem install xcpretty
      - name: Build app
        run: make build_unsigned | xcpretty -c && exit ${PIPESTATUS[0]}
      # Tests require GUI environment, disabled in CI
      #- name: Run tests
      #  run: make clt_tests
